### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by AmauryD** [Lyss-ia/CV#2]
![image](https://user-images.githubusercontent.com/9933000/178192693-ffdbff30-8e32-472b-8571-e7ae606255af.png)

**Comment by Lyss-ia** [comment]
![cat-typing](https://user-images.githubusercontent.com/94531450/178375436-0c96b287-8dc5-4663-87a1-5846116531b7.gif)

![muppet-family-christmas-muppets](https://user-images.githubusercontent.com/94531450/178375469-0016c3b9-0da1-4fb6-9e51-f13c51c0149d.gif)

Est-ce mieux ? 😇

**Comment by AmauryD** [comment]
![image](https://user-images.githubusercontent.com/9933000/178715648-c13aedf7-7330-4640-a056-15c254c84ec2.png)
